theme: jekyll-theme-midnight
title: Foundations of Bioinformatics Class  
description: UCSD BGGN 213 Classwork
logo: "https://i.pinimg.com/236x/95/9f/d9/959fd9195989c13b5e695a0962df6208--science-cartoons-science-humor.jpg"
