theme: jekyll-theme-midnight
title: Foundations of Bioinformatics Class (UCSD BGGN 213) 
description: Classwork
logo: https://i.pinimg.com/236x/95/9f/d9/959fd9195989c13b5e695a0962df6208--science-cartoons-science-humor.jpg
